config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :podcasts

end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
    validates :name, presence: true
    validates :slug, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :set_podcast, only: [:show, :edit, :update, :destroy]

  # GET /podcasts
  # GET /podcasts.json
  def index
    @podcasts = Podcast.all
  end

  # GET /podcasts/1
  # GET /podcasts/1.json
  def show
  end

  # GET /podcasts/new
  def new
    @podcast = Podcast.new
  end

  # GET /podcasts/1/edit
  def edit
  end

  # POST /podcasts
  # POST /podcasts.json
  def create
    @podcast = Podcast.new(podcast_params)

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to @podcast, notice: 'Podcast was successfully created.' }
        format.json { render :show, status: :created, location: @podcast }
      else
        format.html { render :new }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /podcasts/1
  # PATCH/PUT /podcasts/1.json
  def update
    respond_to do |format|
      if @podcast.update(podcast_params)
        format.html { redirect_to @podcast, notice: 'Podcast was successfully updated.' }
        format.json { render :show, status: :ok, location: @podcast }
      else
        format.html { render :edit }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1
  # DELETE /podcasts/1.json
  def destroy
    @podcast.destroy
    respond_to do |format|
      format.html { redirect_to podcasts_url, notice: 'Podcast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_podcast
      @podcast = Podcast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def podcast_params
      params.require(:podcast).permit(:name, :about, :slug)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Earbuds", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Earbuds</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div class="container">

    <%= render "layouts/header" %>

    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-success alert-dismissible", role: "alert") %>
    <% end %>

    <%= yield %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<div class="jumobotron">
    <div class="container">
        <h1>Pages#home</h1>
        <p>Find me in app/views/pages/home.html.erb</p>
    </div><!-- .container -->
</div><!-- .jumbotron -->

app/views/podcasts/_form.html.erb
<div class="panel-body">
  <%= form_for(@podcast) do |f| %>
    <% if @podcast.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@podcast.errors.count, "error") %> prohibited this podcast from being saved:</h2>

        <ul>
        <% @podcast.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :about %><br>
      <%= f.text_area :about, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :slug %><br>
      <%= f.text_field :slug, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Submit", class: "form-control" %>
    </div>
  <% end %>
</div>

app/views/podcasts/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1>Editing podcast</h1>
    </div>
  </div>

  <%= render 'form' %>

  <div class="panel-footer">
    <%= link_to 'Show', @podcast %> |
    <%= link_to 'Back', podcasts_path %>
  </div>
</div>

app/views/podcasts/index.html.erb
<div class="jumobotron">
    <div class="container">
        <h1>Listing podcasts</h1>

        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>About</th>
              <th>Slug</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @podcasts.each do |podcast| %>
              <tr>
                <td><%= podcast.name %></td>
                <td><%= podcast.about %></td>
                <td><%= podcast.slug %></td>
                <td><%= link_to 'Show', podcast %></td>
                <td><%= link_to 'Edit', edit_podcast_path(podcast) %></td>
                <td><%= link_to 'Destroy', podcast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>

        <%= link_to 'New Podcast', new_podcast_path %>
    </div><!-- .container -->
</div><!-- .jumbotron -->

app/views/podcasts/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1>New podcast</h1>
    </div>
  </div>

  <%= render 'form' %>

  <div class="panel-footer">
    <%= link_to 'Back', podcasts_path %>
  </div>
</div>

app/views/podcasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @podcast.name %>
</p>

<p>
  <strong>About:</strong>
  <%= @podcast.about %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @podcast.slug %>
</p>

<%= link_to 'Edit', edit_podcast_path(@podcast) %> |
<%= link_to 'Back', podcasts_path %>